allowBuilds:
  '@parcel/watcher': true
  es5-ext: true
  ttf2woff2: true
minimumReleaseAgeExclude:
  - cssnano-preset-default@9.0.3 || 9.0.5
  - cssnano-utils@7.0.2 || 7.0.3
  - cssnano@9.0.3 || 9.0.5
  - postcss-colormin@9.0.2 || 9.0.3
  - postcss-convert-values@9.0.2 || 9.0.3
  - postcss-discard-comments@9.0.2 || 9.0.3
  - postcss-discard-duplicates@9.0.2 || 9.0.3
  - postcss-discard-empty@9.0.2 || 9.0.3
  - postcss-discard-overridden@9.0.2 || 9.0.3
  - postcss-merge-longhand@9.0.3 || 9.0.4
  - postcss-merge-rules@9.0.3 || 9.0.4
  - postcss-minify-font-values@9.0.2 || 9.0.3
  - postcss-minify-gradients@9.0.2 || 9.0.3
  - postcss-minify-params@9.0.2 || 9.0.3
  - postcss-minify-selectors@9.0.3 || 9.0.4
  - postcss-normalize-charset@9.0.2 || 9.0.3
  - postcss-normalize-display-values@9.0.2 || 9.0.3
  - postcss-normalize-positions@9.0.2 || 9.0.3
  - postcss-normalize-repeat-style@9.0.2 || 9.0.3
  - postcss-normalize-string@9.0.2 || 9.0.3
  - postcss-normalize-timing-functions@9.0.2 || 9.0.3
  - postcss-normalize-unicode@9.0.2 || 9.0.3
  - postcss-normalize-url@9.0.2 || 9.0.3
  - postcss-normalize-whitespace@9.0.2 || 9.0.3
  - postcss-ordered-values@9.0.2 || 9.0.3
  - postcss-reduce-initial@9.0.2 || 9.0.3
  - postcss-reduce-transforms@9.0.2 || 9.0.3
  - postcss-svgo@9.0.2 || 9.0.3
  - postcss-unique-selectors@9.0.2 || 9.0.3
  - stylehacks@9.0.3 || 9.0.4
  - postcss-calc@11.2.0
