allowBuilds:
  '@parcel/watcher': true
  es5-ext: true
  ttf2woff2: true
minimumReleaseAgeExclude:
  - cssnano-preset-default@9.0.3 || 9.0.5 || 9.1.0 || 9.1.1 || 9.3.2
  - cssnano-utils@7.0.2 || 7.0.3 || 8.0.0 || 8.0.1
  - cssnano@9.0.3 || 9.0.5 || 9.1.0 || 9.1.1 || 9.3.2
  - postcss-colormin@9.0.2 || 9.0.3 || 9.0.4
  - postcss-convert-values@9.0.2 || 9.0.3 || 9.0.4 || 9.0.5
  - postcss-discard-comments@9.0.2 || 9.0.3 || 9.0.4
  - postcss-discard-duplicates@9.0.2 || 9.0.3 || 9.0.4
  - postcss-discard-empty@9.0.2 || 9.0.3 || 9.0.4
  - postcss-discard-overridden@9.0.2 || 9.0.3 || 9.0.4
  - postcss-merge-longhand@9.0.3 || 9.0.4 || 9.1.0 || 9.2.1
  - postcss-merge-rules@9.0.3 || 9.0.4 || 9.0.5 || 9.1.2
  - postcss-minify-font-values@9.0.2 || 9.0.3 || 9.0.4
  - postcss-minify-gradients@9.0.2 || 9.0.3 || 9.0.4
  - postcss-minify-params@9.0.2 || 9.0.3 || 9.0.4
  - postcss-minify-selectors@9.0.3 || 9.0.4 || 9.0.5
  - postcss-normalize-charset@9.0.2 || 9.0.3 || 9.0.4
  - postcss-normalize-display-values@9.0.2 || 9.0.3 || 9.0.4
  - postcss-normalize-positions@9.0.2 || 9.0.3 || 9.0.4
  - postcss-normalize-repeat-style@9.0.2 || 9.0.3 || 9.0.4
  - postcss-normalize-string@9.0.2 || 9.0.3 || 9.0.4
  - postcss-normalize-timing-functions@9.0.2 || 9.0.3 || 9.0.4
  - postcss-normalize-unicode@9.0.2 || 9.0.3 || 9.0.4
  - postcss-normalize-url@9.0.2 || 9.0.3 || 9.0.4
  - postcss-normalize-whitespace@9.0.2 || 9.0.3 || 9.0.4
  - postcss-ordered-values@9.0.2 || 9.0.3 || 9.0.4 || 9.0.7
  - postcss-reduce-initial@9.0.2 || 9.0.3 || 9.0.4
  - postcss-reduce-transforms@9.0.2 || 9.0.3 || 9.0.4
  - postcss-svgo@9.0.2 || 9.0.3 || 9.0.4
  - postcss-unique-selectors@9.0.2 || 9.0.3 || 9.0.4
  - stylehacks@9.0.3 || 9.0.4 || 9.0.5
  - postcss-calc@11.2.0
  - yargs@18.2.0
  - '@babel/core@8.0.7'
  - '@babel/helper-compilation-targets@8.0.7'
  - '@babel/helpers@8.0.7'
  - '@babel/parser@8.0.7'
  - '@babel/plugin-transform-block-scoping@8.0.7'
  - '@babel/plugin-transform-for-of@8.0.7'
  - '@babel/preset-env@8.0.7'
  - '@babel/traverse@8.0.7'
  - '@wordpress/dependency-extraction-webpack-plugin@6.57.0'
