<?php

/**
 * News card component — optimized for archive pages.
 *
 * All data resolved from WP's object cache — zero direct DB queries.
 * Category label colors applied via CSS class (term slug) generated by
 * sw_get_taxonomy_top_level_colors_styles() in the parent template.
 *
 * @var array $args {
 *     @type WP_Post $post         Post object with ->term_name, ->term_slug attached.
 *     @type bool    $show_image   Show post thumbnail. Default true.
 *     @type bool    $show_excerpt Show post excerpt. Default false.
 *     @type bool    $is_large     Large card variant (bycat featured). Default false.
 *     @type bool    $is_swiper    Wrap as swiper slide. Default false.
 * }
 */

declare(strict_types=1);

$post_item    = $args['post'];
$show_image   = $args['show_image'] ?? true;
$show_excerpt = $args['show_excerpt'] ?? false;
$is_large     = $args['is_large'] ?? false;
$is_swiper    = $args['is_swiper'] ?? false;

$post_id   = $post_item->ID;
$title     = get_the_title($post_item);
$permalink = get_permalink($post_item);
$term_name = $post_item->term_name ?? '';
$term_slug = $post_item->term_slug ?? '';

// Thumbnail — cache primed by update_post_thumbnail_cache() in parent template
$has_thumb = has_post_thumbnail($post_id);

if ($has_thumb) {
    $thumb_url = get_the_post_thumbnail_url($post_id, 'large');
    $thumb_alt = get_the_post_thumbnail_caption($post_id) ?: $title;
} else {
    $thumb_url = get_template_directory_uri() . '/assets/img/card-placeholder.png';
    $thumb_alt = $title;
}

$excerpt = $show_excerpt ? get_the_excerpt($post_item) : '';

// CSS classes
$classes = ['newcard-content'];
if ($is_large)  $classes[] = 'newcard-lg';
if ($is_swiper) $classes[] = 'swiper-slide';

?>

<a href="<?php echo esc_url($permalink); ?>"
    class="<?php echo esc_attr(implode(' ', $classes)); ?>"
    data-post-id="<?php echo esc_attr((string) $post_id); ?>">

    <?php if ($show_image) : ?>
        <div class="newcard-img-wrap">
            <!-- <span class="sw-gradient-top"></span> -->
            <img
                src="<?php echo esc_url($thumb_url); ?>"
                class="newcard-img"
                alt="<?php echo esc_attr($thumb_alt); ?>"
                loading="lazy">
            <?php if ($term_name) : ?>
                <span class="newcard-label <?php echo esc_attr($term_slug); ?>">
                    <?php echo esc_html($term_name); ?>
                </span>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <div class="newcard-info">
        <time class="text-small newcard-date" datetime="<?php echo esc_attr(get_the_date('Y-m-d', $post_item)); ?>">
            <?php echo esc_html(get_the_date('d.m.Y', $post_item)); ?>
        </time>
    </div>

    <div class="subtitle-text-m newcard-title">
        <?php echo esc_html($title); ?>
    </div>

    <?php if ($excerpt) : ?>
        <div class="text-r newcard-text">
            <?php echo esc_html($excerpt); ?>
        </div>
    <?php endif; ?>

</a>